image: Visual Studio 2017

platform:
  - x86-windows
  - x64-windows

configuration:
  - Debug
  - Release
  - MinSizeRel

init:
  - echo Echoed from init script
  - cd C:\Tools\vcpkg
  - vcpkg version
  - cmake --version

install:
  - cd C:\Tools\vcpkg
  - vcpkg install gtest:%platform% boost-thread:%platform%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake --build . --config %configuration%

