image: Visual Studio 2019

environment:
  matrix:
    # win clang x32
    - CC: clang-cl
      CXX: clang-cl
      base_cflags: -m32
      vcpkg_platform: x86-windows
      additional_cmake_commandline: -GNinja
    # win clang x64
    - CC: clang-cl
      CXX: clang-cl
      vcpkg_platform: x64-windows
      additional_cmake_commandline: -GNinja
    # msvc x32
    - vcpkg_platform: x86-windows
      additional_cmake_commandline: -AWin32
    # msvc x64
    - vcpkg_platform: x64-windows
      additional_cmake_commandline: -Ax64

configuration:
  - Debug
  - Release

for:
  -
    matrix:
      only:
        - configuration: Debug
    environment:
      cmake_build_config: Debug
    before_build:
      - SET CFLAGS="%base_cflags% -g -Og -Wall -Wextra"
      - SET CXXFLAGS=%CFLAGS%

  -
    matrix:
      only:
        - configuration: Release
    environment:
      cmake_build_config: Release
    before_build:
      - SET CFLAGS="%base_cflags% -O2"
      - SET CXXFLAGS=%CFLAGS%

cache: C:\Tools\vcpkg\installed\

init:
  - echo Echoed from init script
  - C:\Tools\vcpkg\vcpkg version
  - cmake --version
  - clang-cl %arch_cflags% --version

install:
  - C:\Tools\vcpkg\vcpkg install gtest:%vcpkg_platform%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake %additional_cmake_commandline%
  - cmake --build . --config %cmake_build_config%

test_script:
  - cmake --build . --config %cmake_build_config% --target run_executable
