image: Visual Studio 2019

environment:
  matrix:
    - platform: x86-windows
      cmake_arch: Win32
      toolchain: "-Tllvm"
    - platform: x64-windows
      cmake_arch: x64
      toolchain: "-Tllvm"
    - platform: x86-windows
      cmake_arch: Win32
      toolchain: ""
    - platform: x64-windows
      cmake_arch: x64
      toolchain: ""


configuration:
  - Debug
  - Release
  - MinSizeRel

cache: C:\Tools\vcpkg\installed\

init:
  - echo Echoed from init script
  - C:\Tools\vcpkg\vcpkg version
  - cmake --version

install:
  - C:\Tools\vcpkg\vcpkg install gtest:%platform%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -A%cmake_arch% %toolchain%
  - cmake --build . --config %configuration%

test_script:
  - cmake --build . --config %configuration% --target run_executable
