image: Visual Studio 2019

environment:
  matrix:
    - compiler: clang
    - compiler: msvc

platform:
  - x86-windows
  - x64-windows

configuration:
  - Debug
  - Release

for:
  -
    matrix:
      only:
        - configuration: Debug
    environment:
      cmake_build_config: Debug
      config_cflags: -g -Og -Wall -Wextra

  -
    matrix:
      only:
        - configuration: Release
    environment:
      cmake_build_config: Release
      config_cflags: -O2

  -
    matrix:
      only:
        - platform: x86-windows
    environment:
      vs_env_script: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars32.bat"

  -
    matrix:
      only:
        - platform: x64-windows
    environment:
      vs_env_script: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

  -
    matrix:
      only:
        - platform: x86-windows
          compiler: clang
    environment:
      base_cflags: -m32

  -
    matrix:
      only:
        - compiler: clang
    environment:
      CC: clang-cl
      CXX: clang-cl
      additional_cmake_commandline: -GNinja

  -
    matrix:
      only:
        - platform: x86-windows
          compiler: msvc
    environment:
      additional_cmake_commandline: -AWin32

  -
    matrix:
      only:
        - platform: x64-windows
          compiler: msvc
    environment:
      additional_cmake_commandline: -Ax64


cache: C:\Tools\vcpkg\installed\

init:
  - echo Echoed from init script
  - C:\Tools\vcpkg\vcpkg version
  - cmake --version
  - clang-cl --version

install:
  - C:\Tools\vcpkg\vcpkg install gtest:%vcpkg_platform%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - call "%vs_env_script%"
  - SET CFLAGS=%base_cflags% %config_cflags%
  - SET CXXFLAGS=%CFLAGS%
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake %additional_cmake_commandline%
  - cmake --build . --config %cmake_build_config%

test_script:
  - cmake --build . --config %cmake_build_config% --target run_executable
