image: Visual Studio 2017

environment:
  matrix:
    - platform: x86-windows
      cmake_arch: Win32
    - platform: x64-windows
      cmake_arch: Win64

configuration:
  - Debug
  - Release
  - MinSizeRel

init:
  - echo Echoed from init script
  - C:\Tools\vcpkg\vcpkg version
  - cmake --version

install:
  - C:\Tools\vcpkg\vcpkg install gtest:%platform%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -A%cmake_arch%
  - cmake --build . --config %configuration%

test_script:
  - cmake --build . --config %configuration% --target run_executable
