image: Visual Studio 2019

environment:
  matrix:
    - platform: x86-windows
      cmake_arch: Win32
      vs_env_script: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars32.bat"
    - platform: x64-windows
      cmake_arch: x64
      vs_env_script: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

configuration:
  - Debug
  - Release
  - DebugClang

for:
  -
    matrix:
      only:
        - configuration: DebugClang
    build_script:
      - echo Echoed from the clang specific build
      - set CC=clang-cl
      - cd %APPVEYOR_BUILD_FOLDER%
      - call "%vs_env_script%"
      - set CMAKE_CXX_COMPILER=clang-cl
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -A%cmake_arch% -G Ninja
      - cmake --build . --config Debug



cache: C:\Tools\vcpkg\installed\

init:
  - echo Echoed from init script
  - C:\Tools\vcpkg\vcpkg version
  - cmake --version
  - clang-cl --version

install:
  - C:\Tools\vcpkg\vcpkg install gtest:%platform%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - call "%vs_env_script%"
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -A%cmake_arch%
  - cmake --build . --config %configuration%

test_script:
  - cmake --build . --config %configuration% --target run_executable
